export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_UP_COMING_MOVIES = "GET_UP_COMING_MOVIES";
export const GET_POPULAR_TV_SHOWS = "GET_POPULAR_TV_SHOWS";
export const GET_POPULAR_ACTORS = "GET_POPULAR_ACTORS";
export const SEARCH_FOR_A_MOVIE = "SEARCH_FOR_A_MOVIE";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES";
export const GET_TV_DETAILS = "GET_TV_DETAILS";
export const GET_SIMILAR_TV = "GET_SIMILAR_TV";
export const GET_ACTOR_DETAILS = "GET_ACTOR_DETAILS";
export const REMOVE_SEARCH_LIST = "REMOVE_SEARCH_LIST";
export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST";
//users

export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER = "LOGIN_USER";
export const AUTH_USER = "AUTH_USER";
export const TOOGLE_TOOL_BARE = "TOOGLE_TOOL_BARE";
